version: 3.7
services:
  script:
    container_name: atpt
    image: "robustetus/atpt:${TAG}"
    entrypoint: /acpipatcher/script.sh
    command:
      - /acpipatcher/bios.exe
    volumes:
      - "./Raw_Tables:${EXTRACTDIR}:z"
      - "./Duplicate_Tables:${DUPLICATEDIR}:z"
      - "${BIOSFILE}:/acpipatcher/bios.exe:z"
