version: 3.7
services:
  script:
    container_name: acpipatcher
    image: "localhost/robustetus/atpt:${TAG}"
    entrypoint: $workdir/script.sh
    command:
      - ${workdir}/bios.exe
    volumes:
      - "./Raw_Tables:${extract_dir}:z"
      - "./Duplicate_Tables:${duplicate_dir}:z"
      - "${BIOSFILE}:${workdir}/bios.exe:z"
