version: 3.7
services:
  script:
    container_name: acpipatcher
    image: "robustetus/acpipatcher:latest"
    working_dir: /acpipatcher
    build: .
    entrypoint: ./script.sh
    command:
      - bios.exe
    volumes:
      - "./Raw_Tables:/acpipatcher/raw_tables:z"
      - "./Duplicate_Tables:/acpipatcher/duplicate_tables:z"
      - "${BIOSFILE}:/acpipatcher/bios.exe:z"
